project:
  type: website

theme:
  light: flatly
  dark: darkly

# theme:
#   light: cosmo
#   dark: [cosmo, theme-dark.scss]

website:
  title: "Davide Fornelli"
  favicon: images/blog_favicon.png
  # reader-mode: true
  site-url: https://www.davidefornelli.com
  search: true
  navbar:
    logo: images/batman_icon.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/davidefornelli/
      - icon: linkedin
        href: https://www.linkedin.com/in/davidefornelli/
      # - icon: twitter
      #   href: https://twitter.com/dvdfornelli
  google-analytics: G-V41FPLBXSF

execute: 
  freeze: auto

# format:
#   html:
#     theme: cosmo
#     css: styles.css 
